version: '3'

services:
  ruby-app:
    build:
      context: ./ruby_app
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
    environment:
      - OLLAMA_API_URL=http://host.docker.internal:11434/api
    volumes:
      - ./ruby_app:/app
    restart: unless-stopped

  python-app:
    build:
      context: ./python_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_API_URL=http://host.docker.internal:11434/api
    volumes:
      - ./python_app:/app
    restart: unless-stopped